# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3-1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1361, 711)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(50, 110, 231, 89))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Sharp = QtWidgets.QLabel(self.widget)
        self.Sharp.setObjectName("Sharp")
        self.verticalLayout.addWidget(self.Sharp)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.doubleSpinBox_returns_min = QtWidgets.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox_returns_min.setObjectName("doubleSpinBox_returns_min")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_returns_min)
        self.doubleSpinBox_maxdrawdown_min = QtWidgets.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox_maxdrawdown_min.setObjectName("doubleSpinBox_maxdrawdown_min")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_maxdrawdown_min)
        self.doubleSpinBox_shape_min = QtWidgets.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox_shape_min.setObjectName("doubleSpinBox_shape_min")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_shape_min)
        self.widget2 = QtWidgets.QWidget(self.splitter)
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.doubleSpinBox_returns_max = QtWidgets.QDoubleSpinBox(self.widget2)
        self.doubleSpinBox_returns_max.setObjectName("doubleSpinBox_returns_max")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_returns_max)
        self.doubleSpinBox_maxdrawdown_max = QtWidgets.QDoubleSpinBox(self.widget2)
        self.doubleSpinBox_maxdrawdown_max.setObjectName("doubleSpinBox_maxdrawdown_max")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_maxdrawdown_max)
        self.doubleSpinBox_shape_max = QtWidgets.QDoubleSpinBox(self.widget2)
        self.doubleSpinBox_shape_max.setObjectName("doubleSpinBox_shape_max")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_shape_max)
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1361, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.doubleSpinBox_returns_min)
        self.label_2.setBuddy(self.doubleSpinBox_maxdrawdown_min)
        self.Sharp.setBuddy(self.doubleSpinBox_shape_min)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Return"))
        self.label_2.setText(_translate("MainWindow", "Markdown"))
        self.Sharp.setText(_translate("MainWindow", "&Sharp"))
        self.label_4.setText(_translate("MainWindow", "Min"))
        self.label_5.setText(_translate("MainWindow", "Max"))
        self.pushButton.setText(_translate("MainWindow", "start"))

