# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(309, 352)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backspaceButton = QtWidgets.QPushButton(self.centralwidget)
        self.backspaceButton.setGeometry(QtCore.QRect(10, 60, 91, 41))
        self.backspaceButton.setObjectName("backspaceButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(110, 60, 91, 41))
        self.clearButton.setObjectName("clearButton")
        self.clearAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearAllButton.setGeometry(QtCore.QRect(210, 60, 91, 41))
        self.clearAllButton.setObjectName("clearAllButton")
        self.clearMemoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearMemoryButton.setGeometry(QtCore.QRect(10, 110, 41, 41))
        self.clearMemoryButton.setObjectName("clearMemoryButton")
        self.readMemoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.readMemoryButton.setGeometry(QtCore.QRect(10, 160, 41, 41))
        self.readMemoryButton.setObjectName("readMemoryButton")
        self.setMemoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.setMemoryButton.setGeometry(QtCore.QRect(10, 210, 41, 41))
        self.setMemoryButton.setObjectName("setMemoryButton")
        self.addToMemoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.addToMemoryButton.setGeometry(QtCore.QRect(10, 260, 41, 41))
        self.addToMemoryButton.setObjectName("addToMemoryButton")
        self.digitButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.digitButton4.setGeometry(QtCore.QRect(60, 160, 41, 41))
        self.digitButton4.setObjectName("digitButton4")
        self.digitButton7 = QtWidgets.QPushButton(self.centralwidget)
        self.digitButton7.setGeometry(QtCore.QRect(60, 110, 41, 41))
        self.digitButton7.setObjectName("digitButton7")
        self.digitButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.digitButton1.setGeometry(QtCore.QRect(60, 210, 41, 41))
        self.digitButton1.setObjectName("digitButton1")
        self.digitButton0 = QtWidgets.QPushButton(self.centralwidget)
        self.digitButton0.setGeometry(QtCore.QRect(60, 260, 41, 41))
        self.digitButton0.setObjectName("digitButton0")
        self.pointButton = QtWidgets.QPushButton(self.centralwidget)
        self.pointButton.setGeometry(QtCore.QRect(110, 260, 41, 41))
        self.pointButton.setObjectName("pointButton")
        self.digitButton5 = QtWidgets.QPushButton(self.centralwidget)
        self.digitButton5.setGeometry(QtCore.QRect(110, 160, 41, 41))
        self.digitButton5.setObjectName("digitButton5")
        self.digitButton8 = QtWidgets.QPushButton(self.centralwidget)
        self.digitButton8.setGeometry(QtCore.QRect(110, 110, 41, 41))
        self.digitButton8.setObjectName("digitButton8")
        self.digitButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.digitButton2.setGeometry(QtCore.QRect(110, 210, 41, 41))
        self.digitButton2.setObjectName("digitButton2")
        self.digitButton6 = QtWidgets.QPushButton(self.centralwidget)
        self.digitButton6.setGeometry(QtCore.QRect(160, 160, 41, 41))
        self.digitButton6.setObjectName("digitButton6")
        self.digitButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.digitButton3.setGeometry(QtCore.QRect(160, 210, 41, 41))
        self.digitButton3.setObjectName("digitButton3")
        self.digitButton9 = QtWidgets.QPushButton(self.centralwidget)
        self.digitButton9.setGeometry(QtCore.QRect(160, 110, 41, 41))
        self.digitButton9.setObjectName("digitButton9")
        self.changeSignButton = QtWidgets.QPushButton(self.centralwidget)
        self.changeSignButton.setGeometry(QtCore.QRect(160, 260, 41, 41))
        self.changeSignButton.setObjectName("changeSignButton")
        self.timesButton = QtWidgets.QPushButton(self.centralwidget)
        self.timesButton.setGeometry(QtCore.QRect(210, 160, 41, 41))
        self.timesButton.setObjectName("timesButton")
        self.powerButton = QtWidgets.QPushButton(self.centralwidget)
        self.powerButton.setGeometry(QtCore.QRect(260, 160, 41, 41))
        self.powerButton.setObjectName("powerButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget)
        self.minusButton.setGeometry(QtCore.QRect(210, 210, 41, 41))
        self.minusButton.setObjectName("minusButton")
        self.squareRootButton = QtWidgets.QPushButton(self.centralwidget)
        self.squareRootButton.setGeometry(QtCore.QRect(260, 110, 41, 41))
        self.squareRootButton.setObjectName("squareRootButton")
        self.reciprocalButton = QtWidgets.QPushButton(self.centralwidget)
        self.reciprocalButton.setGeometry(QtCore.QRect(260, 210, 41, 41))
        self.reciprocalButton.setObjectName("reciprocalButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget)
        self.equalButton.setGeometry(QtCore.QRect(260, 260, 41, 41))
        self.equalButton.setObjectName("equalButton")
        self.divisionButton = QtWidgets.QPushButton(self.centralwidget)
        self.divisionButton.setGeometry(QtCore.QRect(210, 110, 41, 41))
        self.divisionButton.setObjectName("divisionButton")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget)
        self.plusButton.setGeometry(QtCore.QRect(210, 260, 41, 41))
        self.plusButton.setObjectName("plusButton")
        self.display = QtWidgets.QLineEdit(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(10, 10, 291, 31))
        self.display.setObjectName("display")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 309, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backspaceButton.setText(_translate("MainWindow", "Backspace"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.clearAllButton.setText(_translate("MainWindow", "Clear All"))
        self.clearMemoryButton.setText(_translate("MainWindow", "MC"))
        self.readMemoryButton.setText(_translate("MainWindow", "MR"))
        self.setMemoryButton.setText(_translate("MainWindow", "MS"))
        self.addToMemoryButton.setText(_translate("MainWindow", "M+"))
        self.digitButton4.setText(_translate("MainWindow", "4"))
        self.digitButton7.setText(_translate("MainWindow", "7"))
        self.digitButton1.setText(_translate("MainWindow", "1"))
        self.digitButton0.setText(_translate("MainWindow", "0"))
        self.pointButton.setText(_translate("MainWindow", "."))
        self.digitButton5.setText(_translate("MainWindow", "5"))
        self.digitButton8.setText(_translate("MainWindow", "8"))
        self.digitButton2.setText(_translate("MainWindow", "2"))
        self.digitButton6.setText(_translate("MainWindow", "6"))
        self.digitButton3.setText(_translate("MainWindow", "3"))
        self.digitButton9.setText(_translate("MainWindow", "9"))
        self.changeSignButton.setText(_translate("MainWindow", "+-"))
        self.timesButton.setText(_translate("MainWindow", "x"))
        self.powerButton.setText(_translate("MainWindow", "x2"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.squareRootButton.setText(_translate("MainWindow", "Sqrt"))
        self.reciprocalButton.setText(_translate("MainWindow", "1/x"))
        self.equalButton.setText(_translate("MainWindow", "="))
        self.divisionButton.setText(_translate("MainWindow", "/"))
        self.plusButton.setText(_translate("MainWindow", "+"))

